# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-09 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=32, verbose_name='商店名称')),
                ('store_adress', models.CharField(max_length=128, verbose_name='商店地址')),
                ('store_category', models.CharField(default='', max_length=30, verbose_name='商店类别')),
                ('store_sales', models.IntegerField(default='', verbose_name='商店销售量')),
                ('store_img', models.ImageField(default='', upload_to='static/upload/stores', verbose_name='商店图片地址')),
                ('store_status', models.BooleanField(default=True, verbose_name='是否营业')),
                ('store_paise', models.DecimalField(decimal_places=1, default='', max_digits=2, verbose_name='店家评分')),
                ('store_created_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商家',
                'verbose_name_plural': '商家',
                'db_table': 'store',
            },
        ),
    ]
