# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-14 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='bg_img',
            field=models.ImageField(default='', upload_to='static/upload/stores', verbose_name='商店二级页面背景图片'),
        ),
    ]
