# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-29 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='留言内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent_id', models.IntegerField(default=0, verbose_name='父留言ID')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Store')),
            ],
            options={
                'verbose_name': '留言表',
                'verbose_name_plural': '留言表',
                'db_table': 'message',
            },
        ),
    ]
