# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-29 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='publisher',
            new_name='user',
        ),
    ]
