# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-14 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('c_price', models.DecimalField(decimal_places=1, default='', max_digits=4, verbose_name='商品价格')),
                ('c_sales', models.IntegerField(verbose_name='商品销量')),
                ('c_picture', models.ImageField(upload_to='static/upload/stores', verbose_name='商品图片')),
                ('c_material', models.CharField(default='', max_length=100, verbose_name='商品原料')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Store')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'good',
            },
        ),
    ]
