# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-09 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_nickname',
            field=models.CharField(default='', max_length=30, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_password',
            field=models.CharField(default='', max_length=30, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_phone',
            field=models.CharField(default='', max_length=20, verbose_name='手机号'),
        ),
    ]
