# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-09 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191109_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(max_length=50, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_password',
            field=models.CharField(default='', max_length=50, verbose_name='密码'),
        ),
    ]
