# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-10 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191109_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_avatar',
            field=models.ImageField(default='', upload_to='avatar', verbose_name='头像'),
        ),
    ]
