# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-02 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=11, verbose_name='食品名称')),
                ('dish_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='食品价格')),
                ('dish_sale', models.IntegerField(verbose_name='食品销量')),
                ('dish_image', models.ImageField(upload_to='static/upload/foods', verbose_name='食品图片')),
            ],
            options={
                'verbose_name_plural': '面食菜品',
                'db_table': 'Dish_name',
            },
        ),
        migrations.CreateModel(
            name='Noodles_shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noodle_name', models.CharField(default='', max_length=11, verbose_name='面食商店名称')),
                ('noodle_adress', models.CharField(default='', max_length=11, verbose_name='面食商店地址')),
                ('noodle_sales', models.IntegerField(default='', verbose_name='面食商店销售量')),
                ('noodle_img', models.ImageField(default='', upload_to='static/upload/stores', verbose_name='面食商店图片地址')),
                ('noodle_status', models.BooleanField(default=True, verbose_name='是否营业')),
                ('noodle_paise', models.DecimalField(decimal_places=1, default='', max_digits=2, verbose_name='店家评分')),
                ('noodle_created_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '面食',
                'db_table': 'Nooldles_shop',
            },
        ),
        migrations.AddField(
            model_name='dish_name',
            name='noodle_key',
            field=models.ManyToManyField(to='noodles.Noodles_shop'),
        ),
    ]
