# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-02 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noodles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noodles_shop',
            name='noodle_adress',
            field=models.CharField(default='', max_length=128, verbose_name='面食商店地址'),
        ),
        migrations.AlterField(
            model_name='noodles_shop',
            name='noodle_name',
            field=models.CharField(default='', max_length=32, verbose_name='面食商店名称'),
        ),
    ]
