# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-28 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('o_price', models.DecimalField(decimal_places=1, default='', max_digits=4, verbose_name='商品价格')),
                ('o_count', models.IntegerField(verbose_name='商品数量')),
                ('o_number', models.CharField(max_length=50, verbose_name='订单号')),
                ('o_time', models.DateTimeField(auto_now=True, verbose_name='下单时间')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order',
            },
        ),
    ]
